### ISSUE TITLE
開発者がビルドに関する自動テストを利用できる

### ISSUE THREAD

**Issue by Snak0201** [Snak0201/fpb-wwwview#13]
# 理由
- デプロイ後にビルドできないというエラーを防ぎたい
- 手動のテストで気づきにくいバグに気づける可能性が上がる
## 詳細
- ビルドを自動で行うGitHub Actionsを追加する
## 修正メリット／非修正デメリット
- 手動のテストで気づきにくいバグに気づける可能性が上がる
- productionの場合にビルドできるかを先に試すことができる
## 受け入れ条件
- [ ] CIが全てGREENである
- [ ] プッシュ時にビルドをテストするCIが追加されている
## 実装方針
- `.github/workflow`にyarn buildするテストを追加
```
name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x]  # 必要に応じてNode.jsのバージョンを指定

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v2
      with:
        node-version: ${{ matrix.node-version }}

    - name: Install dependencies
      run: yarn install

    - name: Build project
      run: yarn build
```
